source 'https://cpdc-eap.googlesource.com/spec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'FirebaseUI', :path => "../../FirebaseUI.podspec"

target 'FirebaseUIChat' do
end

