# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'FirebaseUI', :path => '~/Development/Firebase/FirebaseUI'

target 'FirebaseUIChat' do

end

target 'FirebaseUIChatTests' do

end

