platform :ios, '8.0'

target 'FirebasePhoneAuthUI' do
  use_frameworks!

  pod 'FirebaseUI/Auth', :path => '../'

  target 'FirebasePhoneAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
