# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'FirebaseAuthUI' do
  use_frameworks!

  pod 'Firebase/Auth'

  target 'FirebaseAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
