platform :ios, '9.0'

target 'FirebaseUI-demo-objc' do

#  used for development from editable sources
  pod 'FirebaseAuthUI', :path => "../../FirebaseUI_dev_auth.podspec"
  pod 'FirebaseDatabaseUI', :path => "../../FirebaseUI_dev_db.podspec"
  pod 'FirebaseStorageUI', :path => "../../FirebaseUI_dev_storage.podspec"
  pod 'FirebaseFacebookAuthUI', :path => "../../FirebaseUI_dev_fb.podspec"
  pod 'FirebaseGoogleAuthUI', :path => "../../FirebaseUI_dev_ggl.podspec"
  pod 'FirebaseTwitterAuthUI', :path => "../../FirebaseUI_dev_tw.podspec"
  pod 'FirebasePhoneAuthUI', :path => "../../FirebaseUI_dev_phone.podspec"

#  used for development from read-only sources
#  pod 'FirebaseAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_auth.podspec"
#  pod 'FirebaseDatabaseUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_db.podspec"
#  pod 'FirebaseStorageUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_storage.podspec"
#  pod 'FirebaseFacebookAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_fb.podspec"
#  pod 'FirebaseGoogleAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_ggl.podspec"
#  pod 'FirebaseTwitterAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_tw.podspec"
#  pod 'FirebasePhoneAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_phone.podspec"

#  used for development from released frameworks
#  use_frameworks!
#  pod 'FirebaseUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI.podspec"

end
