platform :ios, '12.0'

target 'FirebaseUI-demo-objc' do
  use_frameworks!

  pod 'FirebaseUI', :path => '../../'
  pod 'FirebaseAuthUI', :path => '../../'
  pod 'FirebaseDatabaseUI', :path => '../../'
  pod 'FirebaseFirestoreUI', :path => '../../'
  pod 'FirebaseOAuthUI', :path => '../../'
  pod 'FirebasePhoneAuthUI', :path => '../../'
  pod 'FirebaseAnonymousAuthUI', :path => '../../'
  pod 'FirebaseEmailAuthUI', :path => '../../'
  pod 'FirebaseFacebookAuthUI', :path => '../../'
  pod 'FirebaseGoogleAuthUI', :path => '../../'
  pod 'FirebaseStorageUI', :path => '../../'

  pod 'Firebase/DynamicLinks'
end
