platform :ios, '15.0'

target 'FirebaseUI-demo-objc' do
  use_frameworks!

  pod 'FirebaseUI', :path => '../../'
  pod 'FirebaseDatabaseUI', :path => '../../'
  pod 'FirebaseFirestoreUI', :path => '../../'
  pod 'FirebaseStorageUI', :path => '../../'
  
  pod 'Firebase/Auth'  # For anonymous auth in Chat sample
end
