# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'FirebaseGoogleAuthUI' do
  use_frameworks!

  pod 'GoogleSignIn', '~> 5.0'
  pod 'FirebaseUI/Auth', :path => '../'

  target 'FirebaseGoogleAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
