platform :ios, '10.0'

target 'FirebaseAnonymousAuthUI' do
  use_frameworks!

  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth', :path => '../'

  target 'FirebaseAnonymousAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
