# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'FirebaseStorageUI' do
  use_frameworks!

  pod 'Firebase/Storage'
  pod 'SDWebImage', '~> 5.0'

  target 'FirebaseStorageUITests' do
    inherit! :search_paths
    pod 'OCMock'
    pod 'Firebase/Storage'
    pod 'SDWebImage', '~> 5.0'
  end

end
