# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'FirebaseFacebookAuthUI' do
  use_frameworks!

  # The facebook pods generate an unreasonable number of warnings.
  inhibit_all_warnings!

  pod 'FBSDKLoginKit', '~> 5.0'
  pod 'FBSDKCoreKit', '~> 5.0'

  pod 'FirebaseUI/Auth', :path => '../'

  target 'FirebaseFacebookAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
