platform :ios, '8.0'

target 'FirebaseAnonymousAuthUI' do
  use_frameworks!

  pod 'FirebaseAuth', '~> 6.0'
  pod 'FirebaseUI/Auth', :path => '../'

  target 'FirebaseAnonymousAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
