# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'FirebaseGoogleAuthUI' do
  use_frameworks!

  pod 'GoogleSignIn', '~> 6.0'
  pod 'FirebaseAuthUI', :path => '../'

  target 'FirebaseGoogleAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
