# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'FirebaseFirestoreUI' do
  use_frameworks!

  pod 'Firebase/Firestore'

  target 'FirebaseFirestoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
