# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'FirebaseEmailAuthUI' do
  use_frameworks!

  # The dependencies in the FirebaseEmailAuthUI podspec should be here.
  pod 'FirebaseAuthUI', :path => '../'
  pod 'GoogleUtilities/UserDefaults'

  target 'FirebaseEmailAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
