# source 'sso://cpdc-internal/firebase'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'FirebaseEmailAuthUI' do
  use_frameworks!

  pod 'FirebaseUI/Auth', :path => '../'

  target 'FirebaseEmailAuthUITests' do
    inherit! :search_paths
    pod 'OCMock'
  end

end
